apiVersion: v1
kind: Pod
metadata:
  name: "hello-word"
  namespace: default
  labels:
    app: "hello-word"
spec:
  containers:
  - name: hello-word
    image: "marcosmota287/helloword"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always